### ISSUE TITLE
Endpoint get-all-route-rules is not working

### ISSUE THREAD

**Issue by jlachancekffein** [nystudio107/craft3-routemap#22]
The endpoint /actions/route-map/routes/get-all-route-rules?siteId={siteId} is not working and return empty sections and categories.

The reason seems to come from here

```php
src/craftCMS/vendor/nystudio107/craft-routemap/src/services/Routes.php

public function getSectionRouteRules(string $section, string $format = 'Craft', $siteId = null): array{
   ...
  foreach ($sites as $site) {
                    if ($site->hasUrls && ($siteId === null || $site->siteId === $siteId)) {
  ...  
}
```

$site->siteId is a integer
$siteId is a string

So the condition is never met.

Maybe is the Craft CMS version that cause this issue. But maybe cast to the same type will prevent this kind of issue on other version.

Plugin version: 1.1.6
Craft CMS version: 3.5.9

Thanks for your good work.

**Comment by stephanedemotte** [comment]
When i specify the `id` in `actions/route-map/routes/get-all-route-rules?siteId={ID}`, the array is empty.

Maybe the same bug ?

**Comment by khalwat** [comment]
Looks like an easy fix!

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-routemap/commit/dcb858c6b7b47293762c614359ad75a7095f871d

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-routemap": "dev-develop as 1.1.7”,
```
Then do a `composer clear-cache && composer update`

**Comment by Hyra** [comment]
I find casting the `$siteId` rather than the `$site->siteId` to an int to be the actual fix.
