### ISSUE TITLE
Error (Routes::getDbRoutes) in Craft 4 beta 4 / Routemap 4.0.0-beta.1

### ISSUE THREAD

**Issue by stephanedemotte** [nystudio107/craft3-routemap#30]
### Describe the bug
Hello i', trying to use `{% set pages = craft.routeMap.getAllRouteRules('Vue') %}` in a twig template but got this error

```
TypeError: nystudio107\routemap\services\Routes::getDbRoutes(): Argument #1 ($siteId) must be of type ?int, string given, called in /home/stephane/Projects/osteo/vendor/nystudio107/craft-routemap/src/services/Routes.php on line 507 and defined in /home/stephane/Projects/osteo/vendor/nystudio107/craft-routemap/src/services/Routes.php:526
```
I've got a fresh install of craft 4 beta 4.

Thank you !

**Comment by khalwat** [comment]
Fixed in Route Map 4.0.0-beta.2 -> https://github.com/nystudio107/craft-routemap/releases/tag/4.0.0-beta.2
