### ISSUE TITLE
Craft 5 update

### ISSUE THREAD

**Issue by stephanedemotte** [nystudio107/craft3-routemap#33]
Hello

Craft-routemap for Craft 5 could be very usefull for a lot of us :)
I've not the skill to make the update, but if you have time to make it, it's great.

Thank you !

**Comment by khalwat** [comment]
I'm most likely going to port it to Craft 5, assuming there are no major roadblocks involved.

**Comment by khalwat** [comment]
Released for Craft 5: https://github.com/nystudio107/craft-routemap/releases/tag/5.0.0
