### ISSUE TITLE
[FEATURE] Ability to request pathname only

### ISSUE THREAD

**Issue by stursby** [nystudio107/craft3-routemap#5]
Would be great to just get back the pathname instead of the full URL (for example, Nuxt.js wants jus the paths for generating dynamic routes)

So instead of this

```json
[  
  "http://craft.local/news/another-news-entry",
  "http://craft.local/news/my-first-news-entry",
  "http://craft.local/work/fueling-the-good-design-movement",
  "http://craft.local/work/land-of-the-freestyle",
  "http://craft.local/work/case-study-3"
]
```

I would like to get back

```json
[  
  "/news/another-news-entry",
  "/news/my-first-news-entry",
  "/work/fueling-the-good-design-movement",
  "/work/land-of-the-freestyle",
  "/work/case-study-3"
]
```

FYI, my current URL looks like this `http://craft.local/actions/route-map/routes/get-section-urls?section=workDetail,newsDetail`

I know I _could_ just modify the array back in JavaSCript land... but if it's something easy to add to this plugin I figured it doesn't hurt to ask!! Thanks!

**Comment by khalwat** [comment]
Sure, I can do this

**Comment by khalwat** [comment]
Done in 1.1.2: https://github.com/nystudio107/craft-routemap/releases/tag/1.1.2
