### ISSUE TITLE
craft_routes doesn't exist

### ISSUE THREAD

**Issue by clieee** [nystudio107/craft3-routemap#6]
When I request: ```/actions/route-map/routes/get-all-route-rules```

I get the following error:
```Base table or view not found: 1146 Table '[database-name].craft_routes' doesn't exist```

Am I missing something, or has there been an update that brakes your plugin?

**Comment by codyjames** [comment]
This is happening for me as well.

**Comment by khalwat** [comment]
I'm going to guess that Project Config has moved these from a db table and into project config itself

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-routemap/commit/6d867badebd2a53b511586e974f66ccce48872a3

Released as 1.1.6
